#!/bin/bash
# $1 = Имя проекта.
# $2 = Домашняя директория.
# $3 = Директория бинарников.
# $4 = Директория исходников.
#
# Единовременная замена пути к исходникам и имени проекта в файле генератора документации.
if grep -Fq "SPTH" $4/Doxyfile
then
    sed -i -e "s=SPTH=$4=g" $4/Doxyfile
    sed -i -e "s=PRJNAME=$1=g" $4/Doxyfile
fi
# Единовременная замена пути к домашней папке и имени проекта в файле ярлыка.
if grep -Fq "HOME" $4/$1.desktop
then
    sed -i -e "s=HOME=$2=g" $4/$1.desktop
    sed -i -e "s=PRJNAME=$1=g" $4/$1.desktop
fi
# Установка файлов.
rsync -a $3/$1 $2/.$1/
rsync -a $4/$1.png $2/.local/share/icons/hicolor/128x128/apps/
rsync -a $4/$1.desktop $2/.local/share/applications/
